version: "3"
services:
  api:
    build: ./go-backend
    ports:
      - "8080:8080"
  frontend:
    build: ./nextjs-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8080
